#!/bin/bash

set -e -u

which jtcj >/dev/null || {
	echo -e "\n$0 error: 'jtcj' command missing" >&2
	echo "	you need to install ku-jtools package\n" >&2
	exit 1
}

parms=

[ $# = 0 ] && {
	eval $(ku-distroenv)
	parms="--no-repos $DISTRIB_CODENAME"
}

exec jtreset jtcj --batch --no-cd klabs-pkgs makeport $parms "$@"
